export const agreementAbi = [
  {
    type: "function",
    name: "extendCommitmentWindow",
    inputs: [{ name: "newCantChangeUntil", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getDetails",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct AgreementDetails",
        components: [
          { name: "protocolName", type: "string", internalType: "string" },
          {
            name: "contactDetails",
            type: "tuple[]",
            internalType: "struct Contact[]",
            components: [
              { name: "name", type: "string", internalType: "string" },
              { name: "contact", type: "string", internalType: "string" },
            ],
          },
          {
            name: "chains",
            type: "tuple[]",
            internalType: "struct Chain[]",
            components: [
              { name: "assetRecoveryAddress", type: "string", internalType: "string" },
              {
                name: "accounts",
                type: "tuple[]",
                internalType: "struct Account[]",
                components: [
                  { name: "accountAddress", type: "string", internalType: "string" },
                  { name: "childContractScope", type: "uint8", internalType: "enum ChildContractScope" },
                ],
              },
              { name: "caip2ChainId", type: "string", internalType: "string" },
            ],
          },
          {
            name: "bountyTerms",
            type: "tuple",
            internalType: "struct BountyTerms",
            components: [
              { name: "bountyPercentage", type: "uint256", internalType: "uint256" },
              { name: "bountyCapUsd", type: "uint256", internalType: "uint256" },
              { name: "retainable", type: "bool", internalType: "bool" },
              { name: "identity", type: "uint8", internalType: "enum IdentityRequirements" },
              { name: "diligenceRequirements", type: "string", internalType: "string" },
              { name: "aggregateBountyCapUsd", type: "uint256", internalType: "uint256" },
            ],
          },
          { name: "agreementURI", type: "string", internalType: "string" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAssetRecoveryAddress",
    inputs: [{ name: "caip2ChainId", type: "string", internalType: "string" }],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isContractInScope",
    inputs: [{ name: "contractAddress", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  // --- New entries from generated ABI ---
  {
    type: "function",
    name: "getCantChangeUntil",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getChainIds",
    inputs: [],
    outputs: [{ name: "", type: "string[]", internalType: "string[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getBattleChainScopeAddresses",
    inputs: [],
    outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getBattleChainScopeCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getProtocolName",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAgreementURI",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getBountyTerms",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct BountyTerms",
        components: [
          { name: "bountyPercentage", type: "uint256", internalType: "uint256" },
          { name: "bountyCapUsd", type: "uint256", internalType: "uint256" },
          { name: "retainable", type: "bool", internalType: "bool" },
          { name: "identity", type: "uint8", internalType: "enum IdentityRequirements" },
          { name: "diligenceRequirements", type: "string", internalType: "string" },
          { name: "aggregateBountyCapUsd", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getBattleChainCaip2ChainId",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getRegistry",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getChainAccounts",
    inputs: [{ name: "caip2ChainId", type: "string", internalType: "string" }],
    outputs: [
      {
        name: "accounts",
        type: "tuple[]",
        internalType: "struct Account[]",
        components: [
          { name: "accountAddress", type: "string", internalType: "string" },
          { name: "childContractScope", type: "uint8", internalType: "enum ChildContractScope" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setProtocolName",
    inputs: [{ name: "protocolName", type: "string", internalType: "string" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setContactDetails",
    inputs: [
      {
        name: "contactDetails",
        type: "tuple[]",
        internalType: "struct Contact[]",
        components: [
          { name: "name", type: "string", internalType: "string" },
          { name: "contact", type: "string", internalType: "string" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setBountyTerms",
    inputs: [
      {
        name: "bountyTerms",
        type: "tuple",
        internalType: "struct BountyTerms",
        components: [
          { name: "bountyPercentage", type: "uint256", internalType: "uint256" },
          { name: "bountyCapUsd", type: "uint256", internalType: "uint256" },
          { name: "retainable", type: "bool", internalType: "bool" },
          { name: "identity", type: "uint8", internalType: "enum IdentityRequirements" },
          { name: "diligenceRequirements", type: "string", internalType: "string" },
          { name: "aggregateBountyCapUsd", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setAgreementURI",
    inputs: [{ name: "agreementURI", type: "string", internalType: "string" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addOrSetChains",
    inputs: [
      {
        name: "chains",
        type: "tuple[]",
        internalType: "struct Chain[]",
        components: [
          { name: "assetRecoveryAddress", type: "string", internalType: "string" },
          {
            name: "accounts",
            type: "tuple[]",
            internalType: "struct Account[]",
            components: [
              { name: "accountAddress", type: "string", internalType: "string" },
              { name: "childContractScope", type: "uint8", internalType: "enum ChildContractScope" },
            ],
          },
          { name: "caip2ChainId", type: "string", internalType: "string" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addAccounts",
    inputs: [
      { name: "caip2ChainId", type: "string", internalType: "string" },
      {
        name: "newAccounts",
        type: "tuple[]",
        internalType: "struct Account[]",
        components: [
          { name: "accountAddress", type: "string", internalType: "string" },
          { name: "childContractScope", type: "uint8", internalType: "enum ChildContractScope" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "removeAccounts",
    inputs: [
      { name: "caip2ChainId", type: "string", internalType: "string" },
      { name: "accountAddresses", type: "string[]", internalType: "string[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "removeChains",
    inputs: [{ name: "caip2ChainIds", type: "string[]", internalType: "string[]" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
] as const;
