export const attackRegistryAbi = [
  {
    type: "function",
    name: "requestUnderAttack",
    inputs: [{ name: "agreementAddress", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "requestUnderAttackByNonAuthorized",
    inputs: [{ name: "agreementAddress", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getAgreementState",
    inputs: [{ name: "agreementAddress", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint8", internalType: "enum ContractState" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAgreementForContract",
    inputs: [{ name: "contractAddress", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isTopLevelContractUnderAttack",
    inputs: [{ name: "contractAddress", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "approveAttackRequest",
    inputs: [{ name: "agreementAddress", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "rejectAttackRequest",
    inputs: [{ name: "agreementAddress", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "requestPromotion",
    inputs: [{ name: "agreementAddress", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "promote",
    inputs: [{ name: "agreementAddress", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancelPromotion",
    inputs: [{ name: "agreementAddress", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "AgreementStateChanged",
    inputs: [
      { name: "agreementAddress", type: "address", indexed: true, internalType: "address" },
      { name: "previousState", type: "uint8", indexed: false, internalType: "enum ContractState" },
      { name: "newState", type: "uint8", indexed: false, internalType: "enum ContractState" },
    ],
    anonymous: false,
  },
] as const;
