export const attackRegistryAbi = [
  {
    type: "function",
    name: "requestUnderAttack",
    inputs: [{ name: "agreementAddress", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "requestUnderAttackByNonAuthorized",
    inputs: [{ name: "agreementAddress", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getAgreementState",
    inputs: [{ name: "agreementAddress", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint8", internalType: "enum ContractState" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAgreementForContract",
    inputs: [{ name: "contractAddress", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isTopLevelContractUnderAttack",
    inputs: [{ name: "contractAddress", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "approveAttackRequest",
    inputs: [{ name: "agreementAddress", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "rejectAttackRequest",
    inputs: [{ name: "agreementAddress", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "requestPromotion",
    inputs: [{ name: "agreementAddress", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "promote",
    inputs: [{ name: "agreementAddress", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancelPromotion",
    inputs: [{ name: "agreementAddress", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  // --- New entries from generated ABI ---
  {
    type: "function",
    name: "getAgreementInfo",
    inputs: [{ name: "agreementAddress", type: "address", internalType: "address" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct IAttackRegistry.AgreementInfo",
        components: [
          { name: "attackModerator", type: "address", internalType: "address" },
          { name: "deadlineTimestamp", type: "uint256", internalType: "uint256" },
          { name: "promotionRequestedTimestamp", type: "uint256", internalType: "uint256" },
          { name: "attackRequested", type: "bool", internalType: "bool" },
          { name: "attackApproved", type: "bool", internalType: "bool" },
          { name: "promoted", type: "bool", internalType: "bool" },
          { name: "corrupted", type: "bool", internalType: "bool" },
          { name: "isRegistered", type: "bool", internalType: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAuthorizedOwner",
    inputs: [{ name: "contractAddress", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAttackModerator",
    inputs: [{ name: "agreementAddress", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getContractDeployer",
    inputs: [{ name: "contractAddress", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "goToProduction",
    inputs: [{ name: "agreementAddress", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "markCorrupted",
    inputs: [{ name: "agreementAddress", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferAttackModerator",
    inputs: [
      { name: "agreementAddress", type: "address", internalType: "address" },
      { name: "newModerator", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "authorizeAgreementOwner",
    inputs: [
      { name: "contractAddress", type: "address", internalType: "address" },
      { name: "newOwner", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "instantPromote",
    inputs: [{ name: "agreementAddress", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "approveAttack",
    inputs: [{ name: "agreementAddress", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "AgreementStateChanged",
    inputs: [
      { name: "agreementAddress", type: "address", indexed: true, internalType: "address" },
      { name: "newState", type: "uint8", indexed: false, internalType: "enum IAttackRegistry.ContractState" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AgreementOwnerAuthorized",
    inputs: [
      { name: "contractAddress", type: "address", indexed: true, internalType: "address" },
      { name: "authorizedOwner", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AttackModeratorTransferred",
    inputs: [
      { name: "agreementAddress", type: "address", indexed: true, internalType: "address" },
      { name: "newModerator", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ContractRegistered",
    inputs: [
      { name: "contractAddress", type: "address", indexed: true, internalType: "address" },
      { name: "agreementAddress", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
] as const;
